# -*- coding: utf-8 -*-
"""1465_Groceries_eclet.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13qNhglMpDACYtDxf0LoOTKnQO8fDi04E

# ECLET Algorithm using the groceries

## Importing the libraries
"""

!pip install pyECLAT

from google.colab import drive
drive.mount('/content/drive')

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

"""## Data Preprocessing"""

dataset = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Mllab/Datasets/groceries.csv', header = None)

transactions = []
for i in range(0, 9835):
  transactions.append([str(dataset.values[i,j]) for j in range(0, 32)])

print(transactions[0])

"""## Training the Apriori model on the dataset"""

data = pd.DataFrame(transactions)
from pyECLAT import ECLAT
my_eclat = ECLAT(data=data, verbose=True)
rule_indices, rule_supports = my_eclat.fit(min_support=0.003,
                                           min_combination=2,
                                           max_combination=2)

"""## Visualising the results

### Displaying the first results coming directly from the output of the apriori function
"""

results= []

rule_supports

"""### Putting the results well organised into a Pandas DataFrame"""

def inspect(rule_support):
    results = rule_supports.keys()
    supports    = rule_supports.values()
    return list(zip(results, supports))
resultsinDataFrame = pd.DataFrame(inspect(results), columns = [ 'Combinations','Support'])

"""### Displaying the results non sorted"""

resultsinDataFrame

"""### Displaying the results sorted by descending lifts"""

resultsinDataFrame.nlargest(n = 1139, columns = 'Support')